# ================================
# Service para exponer la app ms-api-pos
# ================================

apiVersion: v1                      # Versión de la API para recursos tipo Service
kind: Service                       # Tipo de recurso: Service
metadata:
  name: ms-api-pos-service          # Nombre único del Service

spec:
  selector:
    app: ms-api-pos                 # Selecciona los pods con esta etiqueta (match con el Deployment)

  type: NodePort                    # Tipo de servicio: expone el puerto a nivel de nodo

  ports:
    - port: 3000                    # Puerto lógico del Service dentro del clúster
      targetPort: 3000              # Puerto del contenedor al que redirigir el tráfico
      nodePort: 30009               # Puerto externo accesible desde fuera (ej. http://<IP>:30009)
